eureka:
    instance:
        hostname: localhost
        lease-expiration-duration-in-seconds: 30
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaul-zone: http://${eureka.instance.hostname}:${server.port}/
    server:
        enable-self-preservation: false
server:
    port: 8761
        
---
        
spring:
    profiles: eureka1
    
server:
    port: 8761
    
---

spring:
    profiles: eureka2
    
server:
    port: 8762